server:
  port: 8000
  compression:
    enabled: true
spring:
  datasource:
    url: jdbc:sqlserver://virtualxp:1433;databaseName=SCP
    username: vasja
    password: vasja123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show_sql: false
    database-platform: org.hibernate.dialect.SQLServerDialect
    #hibernate:
  #  hibernate:
      #ddl-auto: create
     # ddl: create
logging:
  level:
    org:
      springframework:
        web: INFO
        beans: INFO
      hibernate: INFO
    com:
       vaadin: INFO

vaadin:
  servlet:
    productionMode: false
    heartbeatInterval: 60
---

spring:
  profiles: production
server:
  port: 8000
logging:
  level:
    org:
      springframework:
        web: INFO
        beans: INFO
      hibernate: INFO
vaadin:
  servlet:
    productionMode: true
    heartbeatInterval: 90
