server:
  port: 8000
  compression:
    enabled: true
spring:
  datasource:
    url: jdbc:sqlserver://vasjasqlserver:1433;databaseName=SCP
    username: sa
    password: sanjose
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    tomcat:
#      min-active: 10
#      max-active: 50
#      min-idle: 5
#      max-idle: 50
#      test-while-idle: true
#      test-on-borrow: true
#      validation-query: SELECT 1
#      validation-interval: 15000
#      #log-abandoned: true
#      remove-abandoned: true
#      time-between-eviction-runs-millis: 5000
#      min-evictable-idle-time-millis: 5000
  jpa:
    show_sql: false
    database-platform: org.hibernate.dialect.SQLServerDialect


#    hibernate:
#      cache:
#        use_second_level_cache: true
#        region:
#          factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
#    hibernate:
#      connection:
#        release_mode: after_statement
#    hibernate:
#    hibernate:
#      ddl-auto: create
#      ddl: create
logging:
  level:
    org:
      sanjose: INFO
      springframework:
        web: INFO
        beans: INFO
      hibernate:
        engine:
          jdbc: INFO
      atmosphere: WARN
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
      apache:
        tomcat:
          jdbc:
            pool: INFO
    com:
       vaadin: INFO

vaadin:
  servlet:
    productionMode: false
    heartbeatInterval: 60
---

spring:
  profiles: production
  datasource:
    #url: jdbc:sqlserver://leon.lan:1433;databaseName=SCP
    url: jdbc:sqlserver://vasjasqlserver:1433;databaseName=SCP
    username: vasja
    password: Vasja123
#    password: tJF/{LJ6h;Z5uW\G
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
server:
  #port: 80
  port: 8000
logging:
  level:
    org:
      sanjose: INFO
      springframework:
        web: INFO
        beans: INFO
      hibernate: INFO
      atmosphere: WARN
vaadin:
  servlet:
    productionMode: true
    heartbeatInterval: 90
    closeIdleSessions: true
