package org.sanjose.views.sys;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DestinoUI extends VerticalLayout {
	protected TextField codigo;
	protected ComboBox clasificacion;
	protected TextField nombreCompleta;
	protected TextField apellidoPaterno;
	protected TextField apellidoMaterno;
	protected ComboBox genero;
	protected TextField direccion;
	protected ComboBox tipoDocumento;
	protected TextField numDocumento;
	protected TextField telefono1;
	protected TextField telefono2;
	protected TextField ruc;
	protected ComboBox tipoDePersona;
	protected ComboBox dependencia;
	protected ComboBox cargo;
	protected Button btnGuardar;
	protected Button btnAnular;
	protected Button btnEliminar;
	protected Button btnNuevo;

	public DestinoUI() {
		Design.read(this);
	}
}
