package org.sanjose.views.sys;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.v7.ui.VerticalLayout;
import com.vaadin.v7.ui.ComboBox;
import com.vaadin.v7.ui.DateField;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ReportesUI extends VerticalLayout {
    protected ComboBox selReporte;
    protected DateField fechaInicial;
    protected DateField fechaFinal;
    protected ComboBox selProyecto;
    protected ComboBox selTercero;
    protected ComboBox selCategoria;
    protected Button btnAceptar;

    public ReportesUI() {
        Design.read(this);
    }
}
