package org.sanjose.views.sys;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Button;
import tm.kod.widgets.numberfield.NumberField;
import com.vaadin.ui.DateField;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class TipoCambioUI extends HorizontalLayout {
    protected DateField fecFecha;
    protected NumberField numTccdolar;
    protected NumberField numTcvdolar;
    protected NumberField numTccmo;
    protected NumberField numTcvmo;
    protected Button btnGuardar;
    protected Button btnIgnorar;
    protected Button btnAnular;

    public TipoCambioUI() {
        Design.read(this);
    }
}
