package org.sanjose.views.rendicion;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import com.vaadin.ui.TextField;
import tm.kod.widgets.numberfield.NumberField;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AnticipoManejoUI extends VerticalLayout {
    protected HorizontalLayout horiz1;
    protected TextField txtCodComprobante;
    protected Button btnCerrar;
    protected HorizontalLayout horiz4;
    protected Grid grid;
    protected Button btnNuevo;
    protected Button btnEliminar;
    protected NumberField txtTotal;

    public AnticipoManejoUI() {
        Design.read(this);
    }
}
