package org.sanjose.views.banco;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BancoManejoUI extends VerticalLayout {
	protected HorizontalLayout horizontalFechas;
	protected DateField fechaDesde;
	protected DateField fechaHasta;
	protected ComboBox selFiltroCuenta;
	protected Button btnNuevoCheque;
	protected Button btnEditar;
	protected Button btnImprimir;
	protected Button btnVerVoucher;
	protected Button btnReporte;
	protected Grid gridBanco;
	protected HorizontalLayout horizontalSaldos;
	protected VerticalLayout verticalSaldoInicial;
	protected TextField iniPEN;
	protected TextField iniUSD;
	protected TextField iniEUR;
	protected Grid gridSaldoInicial;
	protected VerticalLayout verticalSaldoFinal;
	protected TextField finPEN;
	protected TextField finUSD;
	protected TextField finEUR;
	protected Grid gridSaldoFInal;
	protected VerticalLayout verticalSaldoDelDia;
	protected GridLayout gridSaldoDelDia;
	protected Label lblIng;
	protected Label lblEgr;
	protected Label lblSaldo;
	protected Label lblSol;
	protected Label valSolIng;
	protected Label valSolEgr;
	protected Label valSolSaldo;
	protected Label lblDolar;
	protected Label valDolIng;
	protected Label valDolEgr;
	protected Label valDolSaldo;
	protected Label lblEuro;
	protected Label valEuroIng;
	protected Label valEuroEgr;
	protected Label valEuroSaldo;

	public BancoManejoUI() {
		Design.read(this);
	}
}
