package org.sanjose.views.banco;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BancoConciliacionUI extends VerticalLayout {
	protected HorizontalLayout horizontalFechas;
	protected Button expandirContraerBtn;
	protected DateField fechaDesde;
	protected DateField fechaHasta;
	protected ComboBox selFiltroCuenta;
	protected TextField txtSaldoInicial;
	protected VerticalLayout verticalGrid;
	protected TextField txtSaldoFinal;

	public BancoConciliacionUI() {
		Design.read(this);
	}
}
