package org.sanjose.views.dict;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;
import com.vaadin.ui.ComboBox;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DestinoReplaceUI extends HorizontalLayout {
    protected TextField txtDestinoElimnado;
    protected ComboBox selNuevoDestino;
    protected Button btnRemplacar;
    protected Button btnAnular;

    public DestinoReplaceUI() {
        Design.read(this);
    }

}
