package org.sanjose.views.caja;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.DateField;
import com.vaadin.ui.TextField;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CajaManejoUI extends VerticalLayout {
    protected HorizontalLayout horiz1;
    protected DateField fechaDesde;
    protected DateField fechaHasta;
    protected ComboBox selMoneda;
    protected TextField saldoCaja;
    protected Button btnDetallesSaldos;
    protected Button btnReporteImprimirCaja;
    protected HorizontalLayout horiz2;
    protected HorizontalLayout horiz3;
    protected ComboBox selFiltroCaja;
    protected Button nuevaTransferencia;
    protected Button nuevoComprobante;
    protected HorizontalLayout horiz4;
    protected Grid gridCaja;
    protected Button btnVerImprimir;
    protected Button btnModificar;
    protected Button btnEliminar;

    public CajaManejoUI() {
		Design.read(this);
	}
}
