package org.sanjose.views.caja;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CajaGridUI extends VerticalLayout {
	protected HorizontalLayout horizontalCabeza;
	protected DateField fechaDesde;
	protected Label labFechas;
	protected DateField fechaHasta;
	protected Button nuevoComprobante;
	protected Button nuevaTransferencia;
	protected Button editarBtn;
	protected Button enviarBtn;
	protected Button responsablesBtn;
	protected Button imprimirBtn;
	protected Grid gridCaja;

	public CajaGridUI() {
		Design.read(this);
	}
}
