package org.sanjose.views.caja;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;
import org.vaadin.addons.CssCheckBox;
import tm.kod.widgets.numberfield.NumberField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ComprobanteUI extends CssLayout {
    protected VerticalLayout datosGenVertLayout;
    protected VerticalLayout encabezadoVertLayout;
    protected TextField numVoucher;
    protected CssCheckBox chkEnviado;
    protected TextField txtOrigen;
    protected TextField txtNumCombrobante;
    protected VerticalLayout espacioVertLayout;
    protected HorizontalLayout cuentaHorizLayout;
    protected PopupDateField dataFechaComprobante;
    protected OptionGroup tipoProyectoTercero;
    protected ComboBox selProyectoTercero;
    protected TextField saldoProyPEN;
    protected TextField saldoProyUSD;
    protected TextField saldoProyEUR;
    protected VerticalLayout detalleVertLayout;
    protected HorizontalLayout glosaHorizLayout;
    protected TextField glosa;
    protected HorizontalLayout montoHorizLayout;
    protected OptionGroup selMoneda;
    protected NumberField numIngreso;
    protected NumberField numEgreso;
    protected Label lblSaldo;
    protected TextField saldoCaja;
    protected ComboBox selCaja;
    protected FormLayout detallesFormLayout;
    protected VerticalLayout detallesVertLayout;
    protected ComboBox selResponsable;
    protected Button btnResponsable;
    protected ComboBox selTipoMov;
    protected ComboBox selCtaContable;
    protected ComboBox selLugarGasto;
    protected ComboBox selRubroInst;
    protected ComboBox selRubroProy;
    protected ComboBox selFuente;
    protected VerticalLayout docGastoVertLaout;
    protected ComboBox selCodAuxiliar;
    protected Button btnDestino;
    protected PopupDateField fechaDoc;
    protected ComboBox selTipoDoc;
    protected TextField serieDoc;
    protected TextField numDoc;
    protected HorizontalLayout bttnsHorzLayout;
    protected Button eliminarBtn;
    protected Button imprimirBtn;
    protected Button cerrarBtn;
    protected Button guardarBtn;
    protected Button nuevoComprobante;
    protected Button modificarBtn;
    protected Button anularBtn;
    //	protected FormLayout order_summary_layout;
/*	protected Label order_heading;
	protected CssLayout cajaSaldosLayout;
	protected Label saldoLabel1;
	protected Label saldoTotal;*/

	public ComprobanteUI() {
		Design.read(this);
	}
}
