CREATE LOGIN vasja WITH PASSWORD = 'vasja123',  DEFAULT_DATABASE = SCP, DEFAULT_LANGUAGE = Español, CHECK_EXPIRATION = OFF
      GO
 USE [SCP]
GO	 
CREATE USER [vasja] FOR LOGIN [vasja]
GO
USE [SCP]
GO
ALTER ROLE [db_owner] ADD MEMBER [vasja]
GO
