USE [SCP]

GO

SET ANSI_PADDING ON


GO

CREATE NONCLUSTERED INDEX [TipoDestino] ON [dbo].[scp_destino]
(
	[ind_tipodestino] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

GO
